import json
import os

# Configuración de rutas
# Se asume que este script está en una carpeta 'scripts/' hermana de 'js/'
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT_FILE = os.path.join(BASE_DIR, '../js/data/pokedex_es.json')
OUTPUT_FILE = INPUT_FILE  # Sobrescribir el mismo archivo

# Diccionario de movimientos (Inglés -> Español)
MOVES_ES = {
    "Absorb": "Absorber",
    "Acid": "Ácido",
    "Acid Armor": "Armadura Ácida",
    "Acid Spray": "Bomba Ácida",
    "Acrobatics": "Acróbata",
    "Acupressure": "Acupresión",
    "Aerial Ace": "Golpe Aéreo",
    "Aeroblast": "Aerochorro",
    "After You": "Cede Paso",
    "Agility": "Agilidad",
    "Air Cutter": "Aire Afilado",
    "Air Slash": "Tajo Aéreo",
    "Ally Switch": "Cambio Banda",
    "Amnesia": "Amnesia",
    "AncientPower": "Poder Pasado",
    "Aqua Jet": "Acua Jet",
    "Aqua Ring": "Acua Aro",
    "Aqua Tail": "Acua Cola",
    "Arm Thrust": "Empujón",
    "Aromatherapy": "Aromaterapia",
    "Assist": "Ayuda",
    "Assurance": "Buena Baza",
    "Astonish": "Impresionar",
    "Attack Order": "Al Ataque",
    "Attract": "Atracción",
    "Aura Sphere": "Esfera Aural",
    "Aurora Beam": "Rayo Aurora",
    "Autotomize": "Aligerar",
    "Avalanche": "Alud",
    "Baby-Doll Eyes": "Ojitos Tiernos",
    "Barrage": "Presa",
    "Barrier": "Barrera",
    "Baton Pass": "Relevo",
    "Beat Up": "Paliza",
    "Belch": "Eructo",
    "Belly Drum": "Tambor",
    "Bestow": "Ofrenda",
    "Bide": "Venganza",
    "Bind": "Atadura",
    "Bite": "Mordisco",
    "Blast Burn": "Anillo Ígneo",
    "Blaze Kick": "Patada Ígnea",
    "Blizzard": "Ventisca",
    "Block": "Bloqueo",
    "Body Slam": "Golpe Cuerpo",
    "Bolt Strike": "Ataque Fulgor",
    "Bone Club": "Hueso Palo",
    "Bone Rush": "Ataque Óseo",
    "Bonemerang": "Huesomerang",
    "Boomburst": "Estruendo",
    "Bounce": "Bote",
    "Brave Bird": "Pájaro Osado",
    "Brick Break": "Demolición",
    "Brine": "Salmuera",
    "Bubble": "Burbuja",
    "BubbleBeam": "Rayo Burbuja",
    "Bug Bite": "Picadura",
    "Bug Buzz": "Zumbido",
    "Bulk Up": "Corpulencia",
    "Bulldoze": "Terratemblor",
    "Bullet Punch": "Puño Bala",
    "Bullet Seed": "Recurrente",
    "Calm Mind": "Paz Mental",
    "Camouflage": "Camuflaje",
    "Captivate": "Seducción",
    "Celebrate": "Celebración",
    "Charge": "Carga",
    "Charge Beam": "Rayo Carga",
    "Charm": "Encanto",
    "Chatter": "Cháchara",
    "Chip Away": "Guardia Baja",
    "Circle Throw": "Llave Giro",
    "Clamp": "Tenaza",
    "Clear Smog": "Niebla Clara",
    "Close Combat": "A bocajarro",
    "Coil": "Enrosque",
    "Comet Punch": "Puño Cometa",
    "Confide": "Confidencia",
    "Confuse Ray": "Rayo Confuso",
    "Confusion": "Confusión",
    "Constrict": "Restricción",
    "Conversion": "Conversión",
    "Conversion 2": "Conversión 2",
    "Copycat": "Copión",
    "Cosmic Power": "Masa Cósmica",
    "Cotton Guard": "Rizo Algodón",
    "Cotton Spore": "Espora Algodón",
    "Counter": "Contador",
    "Covet": "Antojo",
    "Crabhammer": "Martillazo",
    "Crafty Shield": "Truco Defensa",
    "Cross Chop": "Tajo Cruzado",
    "Cross Poison": "Veneno X",
    "Crunch": "Triturar",
    "Crush Claw": "Garra Brutal",
    "Crush Grip": "Agarre",
    "Curse": "Maldición",
    "Cut": "Corte",
    "Dark Pulse": "Pulso Umbrío",
    "Dark Void": "Brecha Negra",
    "Dazzling Gleam": "Brillo Mágico",
    "Defend Order": "A Defender",
    "Defense Curl": "Rizo Defensa",
    "Defog": "Despejar",
    "Destiny Bond": "Mismo Destino",
    "Detect": "Detección",
    "Diamond Storm": "Tormenta de Diamantes",
    "Dig": "Excavar",
    "Disable": "Anulación",
    "Disarming Voice": "Voz Cautivadora",
    "Discharge": "Chispazo",
    "Dive": "Buceo",
    "Dizzy Punch": "Puño Mareo",
    "Doom Desire": "Deseo Oculto",
    "Double Hit": "Doble Golpe",
    "Double Kick": "Doble Patada",
    "Double Slap": "Doble Bofetón",
    "Double Team": "Doble Equipo",
    "Double-Edge": "Doble Filo",
    "DoubleSlap": "Doble Bofetón",
    "Draco Meteor": "Cometa Draco",
    "Dragon Ascent": "Ascenso Draco",
    "Dragon Breath": "Dragoaliento",
    "Dragon Claw": "Garra Dragón",
    "Dragon Dance": "Danza Dragón",
    "Dragon Pulse": "Pulso Dragón",
    "Dragon Rage": "Furia Dragón",
    "Dragon Rush": "Carga Dragón",
    "Dragon Tail": "Cola Dragón",
    "DragonBreath": "Dragoaliento",
    "Drain Punch": "Puño Drenaje",
    "Draining Kiss": "Beso Drenaje",
    "Dream Eater": "Come Sueños",
    "Drill Peck": "Pico Taladro",
    "Drill Run": "Taladradora",
    "Dual Chop": "Golpe Bis",
    "Dynamic Punch": "Puño Dinámico",
    "DynamicPunch": "Puño Dinámico",
    "Earth Power": "Tierra Viva",
    "Earthquake": "Terremoto",
    "Echoed Voice": "Eco Voz",
    "Eerie Impulse": "Onda Anómala",
    "Egg Bomb": "Bomba Huevo",
    "Electric Terrain": "Campo Eléctrico",
    "Electrify": "Electrificación",
    "Electro Ball": "Bola Voltio",
    "Electroweb": "Electrotela",
    "Embargo": "Embargo",
    "Ember": "Ascuas",
    "Encore": "Otra Vez",
    "Endeavor": "Esfuerzo",
    "Endure": "Aguante",
    "Energy Ball": "Energibola",
    "Entrainment": "Danza Amiga",
    "Eruption": "Estallido",
    "Explosion": "Explosión",
    "Extrasensory": "Paranormal",
    "Extreme Speed": "Velocidad Extrema",
    "ExtremeSpeed": "Velocidad Extrema",
    "Facade": "Imagen",
    "Faint Attack": "Finta",
    "Fairy Lock": "Cerrojo Feérico",
    "Fairy Wind": "Viento Feérico",
    "Fake Out": "Sorpresa",
    "Fake Tears": "Llanto Falso",
    "False Swipe": "Falsotortazo",
    "Feather Dance": "Danza Pluma",
    "FeatherDance": "Danza Pluma",
    "Feint": "Amago",
    "Feint Attack": "Finta",
    "Fell Stinger": "Aguijón Letal",
    "Fiery Dance": "Danza Llama",
    "Final Gambit": "Sacrificio",
    "Fire Blast": "Llamarada",
    "Fire Fang": "Colmillo Ígneo",
    "Fire Pledge": "Voto Fuego",
    "Fire Punch": "Puño Fuego",
    "Fire Spin": "Giro Fuego",
    "Fissure": "Fisura",
    "Flail": "Azote",
    "Flame Burst": "Pirotecnia",
    "Flame Charge": "Nitrocarga",
    "Flame Wheel": "Rueda Fuego",
    "Flamethrower": "Lanzallamas",
    "Flare Blitz": "Envite Ígneo",
    "Flash": "Destello",
    "Flash Cannon": "Foco Resplandor",
    "Flatter": "Camelo",
    "Fling": "Lanzamiento",
    "Flower Shield": "Defensa Floral",
    "Fly": "Vuelo",
    "Flying Press": "Plancha Voladora",
    "Focus Blast": "Onda Certera",
    "Focus Energy": "Foco Energía",
    "Focus Punch": "Puño Certero",
    "Follow Me": "Señuelo",
    "Force Palm": "Palmeo",
    "Foresight": "Profecía",
    "Forest's Curse": "Condena Silvana",
    "Foul Play": "Juego Sucio",
    "Freeze-Dry": "Liofilización",
    "Frenzy Plant": "Planta Feroz",
    "Frost Breath": "Vaho Gélido",
    "Frustration": "Frustración",
    "Fury Attack": "Ataque Furia",
    "Fury Cutter": "Corte Furia",
    "Fury Swipes": "Golpes Furia",
    "Fusion Bolt": "Rayo Fusión",
    "Fusion Flare": "Llama Fusión",
    "Future Sight": "Premonición",
    "Gastro Acid": "Bilis",
    "Gear Grind": "Rueda Doble",
    "Geomancy": "Geocontrol",
    "Giga Drain": "Gigadrenado",
    "Giga Impact": "Gigaimpacto",
    "Glaciate": "Mundo Gélido",
    "Glare": "Mal de Ojo",
    "Grass Knot": "Hierba Lazo",
    "Grass Pledge": "Voto Planta",
    "Grass Whistle": "Silbato",
    "GrassWhistle": "Silbato",
    "Grassy Terrain": "Campo de Hierba",
    "Gravity": "Gravedad",
    "Growl": "Gruñido",
    "Growth": "Crecimiento",
    "Grudge": "Rabia",
    "Guard Split": "Isoguardia",
    "Guard Swap": "Cambia Defensa",
    "Guillotine": "Guillotina",
    "Gunk Shot": "Lanza Mugre",
    "Gust": "Tornado",
    "Gyro Ball": "Giro Bola",
    "Hail": "Granizo",
    "Hammer Arm": "Machada",
    "Happy Hour": "Paga Extra",
    "Harden": "Fortaleza",
    "Haze": "Niebla",
    "Head Charge": "Ariete",
    "Head Smash": "Testarazo",
    "Headbutt": "Golpe Cabeza",
    "Heal Bell": "Campana Cura",
    "Heal Block": "Anticura",
    "Heal Order": "Auxilio",
    "Heal Pulse": "Pulso Cura",
    "Healing Wish": "Deseo Cura",
    "Heart Stamp": "Arrumaco",
    "Heart Swap": "Intercambio",
    "Heat Crash": "Golpe Calor",
    "Heat Wave": "Onda Ígnea",
    "Heavy Slam": "Cuerpo Pesado",
    "Helping Hand": "Refuerzo",
    "Hex": "Infortunio",
    "Hi Jump Kick": "Patada Salto Alta",
    "Hidden Power": "Poder Oculto",
    "High Jump Kick": "Patada Salto Alta",
    "Hold Back": "Clemencia",
    "Hold Hands": "Manos Juntas",
    "Hone Claws": "Afilagarras",
    "Horn Attack": "Cornada",
    "Horn Drill": "Perforador",
    "Horn Leech": "Asta Drenaje",
    "Howl": "Aullido",
    "Hurricane": "Vendaval",
    "Hydro Cannon": "Hidrocañón",
    "Hydro Pump": "Hidrobomba",
    "Hyper Beam": "Hiperrayo",
    "Hyper Fang": "Hipercolmillo",
    "Hyper Voice": "Vozarrón",
    "Hyperspace Fury": "Paso Dimensional",
    "Hyperspace Hole": "Paso Dimensional",
    "Hypnosis": "Hipnosis",
    "Ice Ball": "Bola Hielo",
    "Ice Beam": "Rayo Hielo",
    "Ice Burn": "Llama Gélida",
    "Ice Fang": "Colmillo Hielo",
    "Ice Punch": "Puño Hielo",
    "Ice Shard": "Canto Helado",
    "Icicle Crash": "Chuzos",
    "Icicle Spear": "Carámbano",
    "Icy Wind": "Viento Hielo",
    "Imprison": "Cerca",
    "Incinerate": "Calcinación",
    "Inferno": "Infierno",
    "Infestation": "Acoso",
    "Ingrain": "Arraigo",
    "Ion Deluge": "Cortina Plasma",
    "Iron Defense": "Defensa Férrea",
    "Iron Head": "Cabeza de Hierro",
    "Iron Tail": "Cola Férrea",
    "Judgment": "Sentencia",
    "Jump Kick": "Patada Salto",
    "Karate Chop": "Golpe Kárate",
    "Kinesis": "Kinético",
    "King's Shield": "Escudo Real",
    "Knock Off": "Desarme",
    "Land's Wrath": "Fuerza Telúrica",
    "Last Resort": "Última Baza",
    "Lava Plume": "Humareda",
    "Leaf Blade": "Hoja Aguda",
    "Leaf Storm": "Lluevehojas",
    "Leaf Tornado": "Ciclón de Hojas",
    "Leech Life": "Chupa Vidas",
    "Leech Seed": "Drenadoras",
    "Leer": "Malicioso",
    "Lick": "Lengüetazo",
    "Light of Ruin": "Luz Aniquiladora",
    "Light Screen": "Pantalla de Luz",
    "Lock-On": "Fijar Blanco",
    "Lovely Kiss": "Beso Amoroso",
    "Low Kick": "Patada Baja",
    "Low Sweep": "Puntapié",
    "Lucky Chant": "Cántico",
    "Lunar Dance": "Danza Lunar",
    "Luster Purge": "Resplandor",
    "Mach Punch": "Ultrapuño",
    "Magic Coat": "Capa Mágica",
    "Magic Room": "Zona Mágica",
    "Magical Leaf": "Hoja Mágica",
    "Magma Storm": "Lluvia Ígnea",
    "Magnet Bomb": "Bomba Imán",
    "Magnet Rise": "Levimagnetón",
    "Magnetic Flux": "Aura Magnética",
    "Magnitude": "Magnitud",
    "Mat Block": "Escudo Tatami",
    "Me First": "Yo Primero",
    "Mean Look": "Mal de Ojo",
    "Meditate": "Meditación",
    "Mega Drain": "Megaagotar",
    "Mega Kick": "Megapatada",
    "Mega Punch": "Megapuño",
    "Megahorn": "Megacuerno",
    "Memento": "Legado",
    "Metal Burst": "Represión Metal",
    "Metal Claw": "Garra Metal",
    "Metal Sound": "Eco Metálico",
    "Meteor Mash": "Puño Meteoro",
    "Meteorobola": "Meteorobola",
    "Metronome": "Metrónomo",
    "Milk Drink": "Batido",
    "Mimic": "Mimético",
    "Mind Reader": "Telépata",
    "Minimize": "Reducción",
    "Miracle Eye": "Gran Ojo",
    "Mirror Coat": "Manto Espejo",
    "Mirror Move": "Movimiento Espejo",
    "Mirror Shot": "Disparo Espejo",
    "Mist": "Neblina",
    "Mist Ball": "Bola Neblina",
    "Misty Terrain": "Campo de Niebla",
    "Moonblast": "Fuerza Lunar",
    "Moonlight": "Luz Lunar",
    "Morning Sun": "Sol Matinal",
    "Mud Bomb": "Bomba Fango",
    "Mud Shot": "Disparo Lodo",
    "Mud Sport": "Chapoteo Lodo",
    "Mud-Slap": "Bofetón Lodo",
    "Muddy Water": "Agua Lodosa",
    "Mystical Fire": "Llama Embrujada",
    "Nasty Plot": "Maquinación",
    "Natural Gift": "Don Natural",
    "Nature Power": "Adaptación",
    "Needle Arm": "Machada",
    "Night Daze": "Brecha Negra",
    "Night Shade": "Tinieblas",
    "Night Slash": "Tajo Umbrío",
    "Nightmare": "Pesadilla",
    "Noble Roar": "Rugido de Guerra",
    "Nuzzle": "Moflete Estático",
    "Oblivion Wing": "Ala Mortífera",
    "Octazooka": "Pulpocañón",
    "Odor Sleuth": "Rastreo",
    "Ominous Wind": "Viento Aciago",
    "Origin Pulse": "Pulso Primigenio",
    "Outrage": "Enfado",
    "Overheat": "Sofoco",
    "Pain Split": "Divide Dolor",
    "Parabolic Charge": "Carga Parábola",
    "Parting Shot": "Última Palabra",
    "Pay Day": "Día de Pago",
    "Payback": "Vendetta",
    "Peck": "Picotazo",
    "Perish Song": "Canto Mortal",
    "Petal Blizzard": "Tormenta Floral",
    "Petal Dance": "Danza Pétalo",
    "Phantom Force": "Golpe Fantasma",
    "Pin Missile": "Pin Misil",
    "Play Nice": "Camaradería",
    "Play Rough": "Carantoña",
    "Pluck": "Picoteo",
    "Poison Fang": "Colmillo Veneno",
    "Poison Gas": "Gas Venenoso",
    "Poison Jab": "Puya Nociva",
    "Poison Powder": "Polvo Veneno",
    "Poison Sting": "Picotazo Venenoso",
    "Poison Tail": "Cola Veneno",
    "PoisonPowder": "Polvo Veneno",
    "Pound": "Destructor",
    "Powder": "Polvo Explosivo",
    "Powder Snow": "Nieve Polvo",
    "Power Gem": "Joya de Luz",
    "Power Split": "Isopotencia",
    "Power Swap": "Isofuerza",
    "Power Trick": "Truco Fuerza",
    "Power Whip": "Latigazo",
    "Power-Up Punch": "Puño Incremento",
    "Precipice Blades": "Filo del Abismo",
    "Present": "Presente",
    "Protect": "Protección",
    "Psybeam": "Psicorrayo",
    "Psych Up": "Más Psique",
    "Psychic": "Psíquico",
    "Psycho Boost": "Psicoataque",
    "Psycho Cut": "Psicocorte",
    "Psycho Shift": "Psicocambio",
    "Psyshock": "Psicocarga",
    "Psystrike": "Onda Mental",
    "Psywave": "Psicoonda",
    "Punishment": "Castigo",
    "Pursuit": "Persecución",
    "Quash": "Último Lugar",
    "Quick Attack": "Ataque Rápido",
    "Quick Guard": "Anticipo",
    "Quiver Dance": "Danza Aleteo",
    "Rage": "Furia",
    "Rage Powder": "Polvo Ira",
    "Rain Dance": "Danza Lluvia",
    "Rapid Spin": "Giro Rápido",
    "Razor Leaf": "Hoja Afilada",
    "Razor Shell": "Concha Filo",
    "Razor Wind": "Viento Cortante",
    "Recover": "Recuperación",
    "Recycle": "Reciclaje",
    "Reflect": "Reflejo",
    "Reflect Type": "Clonatipo",
    "Refresh": "Alivio",
    "Relic Song": "Canto Arcaico",
    "Rest": "Descanso",
    "Retaliate": "Represalia",
    "Return": "Retribución",
    "Revenge": "Desquite",
    "Reversal": "Inversión",
    "Roar": "Rugido",
    "Roar of Time": "Distorsión",
    "Rock Blast": "Pedrada",
    "Rock Climb": "Treparrocas",
    "Rock Polish": "Pulimento",
    "Rock Slide": "Avalancha",
    "Rock Smash": "Golpe Roca",
    "Rock Throw": "Lanzarrocas",
    "Rock Tomb": "Tumba Rocas",
    "Rock Wrecker": "Romperrocas",
    "Role Play": "Imitación",
    "Rolling Kick": "Patada Giro",
    "Rollout": "Desenrollar",
    "Roost": "Respiro",
    "Rototiller": "Fertilizante",
    "Round": "Canon",
    "Sacred Fire": "Fuego Sagrado",
    "Sacred Sword": "Espada Santa",
    "Safeguard": "Velo Sagrado",
    "Sand Tomb": "Bucle Arena",
    "Sand-Attack": "Ataque Arena",
    "Sandstorm": "Tormenta Arena",
    "Scald": "Escaldar",
    "Scary Face": "Cara Susto",
    "Scratch": "Arañazo",
    "Screech": "Chirrido",
    "Searing Shot": "Bomba Ígnea",
    "Secret Power": "Daño Secreto",
    "Secret Sword": "Sable Místico",
    "Seed Bomb": "Bomba Germen",
    "Seed Flare": "Fogonazo",
    "Seismic Toss": "Movimiento Sísmico",
    "Self-Destruct": "Autodestrucción",
    "Selfdestruct": "Autodestrucción",
    "Shadow Ball": "Bola Sombra",
    "Shadow Claw": "Garra Umbría",
    "Shadow Force": "Golpe Umbrío",
    "Shadow Punch": "Puño Sombra",
    "Shadow Sneak": "Sombra Vil",
    "Sharpen": "Afilar",
    "Sheer Cold": "Frío Polar",
    "Shell Smash": "Rompecoraza",
    "Shift Gear": "Cambio de Marcha",
    "Shock Wave": "Onda de Choque",
    "Signal Beam": "Doble Rayo",
    "Silver Wind": "Viento Plata",
    "Simple Beam": "Onda Simple",
    "Sing": "Canto",
    "Sketch": "Esquema",
    "Skill Swap": "Intercambio",
    "Skull Bash": "Cabezazo",
    "Sky Attack": "Ataque Aéreo",
    "Sky Drop": "Caída Libre",
    "Sky Uppercut": "Gancho Alto",
    "Slack Off": "Relajo",
    "Slam": "Atizar",
    "Slash": "Cuchillada",
    "Sleep Powder": "Somnífero",
    "Sleep Talk": "Sonámbulo",
    "Sludge": "Residuos",
    "Sludge Bomb": "Bomba Lodo",
    "Sludge Wave": "Onda Tóxica",
    "Smack Down": "Antiaéreo",
    "Smelling Salts": "Estímulo",
    "SmellingSalt": "Estímulo",
    "Smog": "Polución",
    "SmokeScreen": "Pantalla de Humo",
    "Snarl": "Alarido",
    "Snatch": "Robo",
    "Snore": "Ronquido",
    "Soak": "Anegar",
    "Soft-Boiled": "Amortiguador",
    "Softboiled": "Amortiguador",
    "Solar Beam": "Rayo Solar",
    "SolarBeam": "Rayo Solar",
    "Sonic Boom": "Bomba Sónica",
    "SonicBoom": "Bomba Sónica",
    "Spacial Rend": "Corte Vacío",
    "Spark": "Chispa",
    "Spider Web": "Telaraña",
    "Spike Cannon": "Clavo Cañón",
    "Spikes": "Púas",
    "Spiky Shield": "Barrera Espinosa",
    "Spit Up": "Escupir",
    "Spite": "Rencor",
    "Splash": "Salpicadura",
    "Spore": "Espora",
    "Stealth Rock": "Trampa Rocas",
    "Steam Eruption": "Chorro de Vapor",
    "Steamroller": "Rodillo de Púas",
    "Steel Wing": "Ala de Acero",
    "Sticky Web": "Red Viscosa",
    "Stockpile": "Reserva",
    "Stomp": "Pisotón",
    "Stone Edge": "Roca Afilada",
    "Stored Power": "Poder Reserva",
    "Storm Throw": "Llave Corsé",
    "Strength": "Fuerza",
    "String Shot": "Disparo Demora",
    "Struggle": "Combate",
    "Struggle Bug": "Estoicismo",
    "Stun Spore": "Paralizador",
    "Submission": "Sumisión",
    "Substitute": "Sustituto",
    "Sucker Punch": "Golpe Bajo",
    "Sunny Day": "Día Soleado",
    "Super Fang": "Superdiente",
    "Superpower": "Fuerza Bruta",
    "Supersonic": "Supersónico",
    "Surf": "Surf",
    "Swagger": "Contoneo",
    "Swallow": "Tragar",
    "Sweet Kiss": "Beso Dulce",
    "Sweet Scent": "Dulce Aroma",
    "Swift": "Rapidez",
    "Switcheroo": "Trapicheo",
    "Swords Dance": "Danza Espada",
    "Synchronoise": "Sincrorruido",
    "Synthesis": "Síntesis",
    "Tackle": "Placaje",
    "Tail Glow": "Ráfaga",
    "Tail Slap": "Plumerazo",
    "Tail Whip": "Látigo",
    "Tailwind": "Viento Afín",
    "Take Down": "Derribo",
    "Taunt": "Mofa",
    "Techno Blast": "Tecno Shock",
    "Teeter Dance": "Danza Caos",
    "Telekinesis": "Telequinesis",
    "Teleport": "Teletransporte",
    "Thief": "Ladrón",
    "Thousand Arrows": "Mil Flechas",
    "Thousand Waves": "Mil Temblores",
    "Thrash": "Golpe",
    "Thunder": "Trueno",
    "Thunder Fang": "Colmillo Rayo",
    "Thunder Punch": "Puño Trueno",
    "Thunder Shock": "Impactrueno",
    "Thunder Wave": "Onda Trueno",
    "Thunderbolt": "Rayo",
    "ThunderPunch": "Puño Trueno",
    "ThunderShock": "Impactrueno",
    "Tickle": "Cosquillas",
    "Topsy-Turvy": "Reversión",
    "Torment": "Tormento",
    "Toxic": "Tóxico",
    "Toxic Spikes": "Púas Tóxicas",
    "Transform": "Transformación",
    "Tri Attack": "Triataque",
    "Trick": "Truco",
    "Trick Room": "Espacio Raro",
    "Trick-or-Treat": "Halloween",
    "Triple Kick": "Triple Patada",
    "Trump Card": "As Oculto",
    "Twineedle": "Doble Ataque",
    "Twister": "Ciclón",
    "U-turn": "Ida y Vuelta",
    "Uproar": "Alboroto",
    "V-create": "V de Fuego",
    "Vacuum Wave": "Onda Vacío",
    "Venom Drench": "Trampa Venenosa",
    "Venoshock": "Carga Tóxica",
    "Vice Grip": "Agarre",
    "ViceGrip": "Agarre",
    "Vine Whip": "Látigo Cepa",
    "Vital Throw": "Tiro Vital",
    "Volt Switch": "Voltiocambio",
    "Volt Tackle": "Placaje Eléctrico",
    "Wake-Up Slap": "Espabila",
    "Water Gun": "Pistola Agua",
    "Water Pledge": "Voto Agua",
    "Water Pulse": "Hidropulso",
    "Water Shuriken": "Shuriken de Agua",
    "Water Sport": "Hidrochorro",
    "Water Spout": "Salpicar",
    "Waterfall": "Cascada",
    "Weather Ball": "Meteorobola",
    "Whirlpool": "Torbellino",
    "Whirlwind": "Remolino",
    "Wide Guard": "Vastaguardia",
    "Wild Charge": "Voltio Cruel",
    "Will-O-Wisp": "Fuego Fatuo",
    "Wing Attack": "Ataque Ala",
    "Wish": "Deseo",
    "Withdraw": "Refugio",
    "Wonder Room": "Zona Extraña",
    "Wood Hammer": "Mazazo",
    "Work Up": "Avivar",
    "Worry Seed": "Abatidoras",
    "Wrap": "Constricción",
    "Wring Out": "Estrujón",
    "X-Scissor": "Tijera X",
    "Yawn": "Bostezo",
    "Zap Cannon": "Electrocañón",
    "Zen Headbutt": "Cabezazo Zen"
}

def main():
    try:
        print(f"Leyendo archivo: {INPUT_FILE}")
        with open(INPUT_FILE, 'r', encoding='utf-8') as f:
            pokedex = json.load(f)
        
        count = 0
        translated_count = 0
        
        print(f"Procesando {len(pokedex)} entradas...")

        for key, pkm in pokedex.items():
            if 'moves' in pkm:
                for move in pkm['moves']:
                    original_name = move.get('name')
                    if original_name in MOVES_ES:
                        move['name'] = MOVES_ES[original_name]
                        translated_count += 1
                    # Algunos nombres pueden venir con espacios o guiones diferentes, 
                    # pero el diccionario cubre los casos exactos del JSON proporcionado.
            count += 1

        # Guardar cambios
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            json.dump(pokedex, f, indent=2, ensure_ascii=False)
        
        print(f"¡Éxito! Se han traducido {translated_count} movimientos en {count} Pokémon.")
        print(f"Archivo guardado en: {OUTPUT_FILE}")

    except FileNotFoundError:
        print(f"Error: No se encontró el archivo en {INPUT_FILE}")
    except Exception as e:
        print(f"Ocurrió un error: {e}")

if __name__ == "__main__":
    main()
